// Firebase reducer constants
export const FIREBASE_FETCH_DATA_REQUEST = "FIREBASE_FETCH_DATA_REQUEST";
export const FIREBASE_FETCH_DATA_FAILURE = "FIREBASE_FETCH_DATA_FAILURE";
export const FIREBASE_FETCH_USER_DATA_SUCCESS = "FIREBASE_FETCH_USER_DATA_SUCCESS";
export const FIREBASE_CREATE_USER_DOC_SUCCESS = "FIREBASE_CREATE_USER_DOC_SUCCESS";
