// Categories reducer constants
export const CATEGORIES_FETCH_DATA_REQUEST = "CATEGORIES_FETCH_DATA_REQUEST";
export const CATEGORIES_FETCH_DATA_SUCCESS = "CATEGORIES_FETCH_DATA_SUCCESS";
export const CATEGORIES_FETCH_DATA_FAILURE = "CATEGORIES_FETCH_DATA_FAILURE";
