// Contentful reducer data constants
export const CONTENTFUL_FETCH_DATA_REQUEST = "CONTENTFUL_FETCH_DATA_REQUEST";
export const CONTENTFUL_FETCH_DATA_SUCCESS = "CONTENTFUL_FETCH_DATA_SUCCESS";
export const CONTENTFUL_FETCH_DATA_FAILURE = "CONTENTFUL_FETCH_DATA_FAILURE";
